export const theme = {
  colors: {
    background: '#f4f7fb',
    surface: '#ffffff',
    surfaceMuted: '#eef3fb',
    surfaceStrong: '#dfe9fb',
    primary: '#2f6df6',
    primaryStrong: '#1d58dc',
    primarySoft: '#e8f0ff',
    text: '#162033',
    textSecondary: '#46536b',
    textMuted: '#93a0b3',
    border: '#e6ecf4',
    shadow: '#172235',
    dark: '#0f1a30',
    green: '#1ba56a',
    greenBg: '#eaf8f0',
    yellow: '#eead30',
    yellowBg: '#fff6e3',
    red: '#e85a5a',
    redBg: '#feebeb',
    dataPanelBg: '#0B1628',
    dataPanelBorder: '#1e3a5f',
    chartLine: '#60A5FA',
    chartLineFaded: '#3b82f6',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  radius: {
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
  },
  shadows: {
    card: {
      shadowColor: '#172235',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.08,
      shadowRadius: 24,
      elevation: 6,
    },
    floating: {
      shadowColor: '#172235',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.14,
      shadowRadius: 20,
      elevation: 10,
    },
  },
};
